saveExact: true
minimumReleaseAge: 4320 # 3 days
allowBuilds:
  core-js-bundle: true
  core-js-pure: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@compas-oscd/core'
  - '@compas-oscd/open-scd'
  - '@compas-oscd/plugins'
  - '@compas-oscd/xml'
