sonar.organization=com-pas
sonar.projectKey=com-pas_compas-open-scd
sonar.sources=packages/compas-open-scd/src
sonar.tests=packages/compas-open-scd/test
sonar.javascript.lcov.reportPaths=packages/compas-open-scd/coverage/lcov.info
sonar.exclusions=**/*.test.snap.js
