# SPDX-FileCopyrightText: 2026 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: SonarCloud Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          fetch-depth: 0
          submodules: "true"

      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          cache: true
          
      - name: Use Node.js 24.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: pnpm ci

      - name: Build
        run: pnpm run-script build

      - name: Run tests with coverage
        run: pnpm run-script test

      - name: Save PR number to file
        if: ${{ github.event_name == 'pull_request' }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: echo "$PR_NUMBER" > PR_NUMBER.txt

      - name: Archive PR number
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: PR_NUMBER
          path: PR_NUMBER.txt

      - name: Archive coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage
          path: coverage/
